var test = "hallo";
var welt = "welt";
var zahl = 90;
var zahl2 = 100;
console.log(zahl2 * zahl);
var zahl = 20;
var zahl1 = 200;
var ergebnis = (zahl / zahl1) * 100;
var prozent = "%";
console.log(ergebnis + " %");
var Emissionen = "Emissionen";
var der = "der";
var Welt = "Welt:";
console.log(Emissionen + der + Welt);
var afrika = 1235.5;
var südamerika = 1261.5;
var europa = 4209.3;
var nordamerika = 6035.6;
var asien = 16274.1;
var australien = 2100;
var afrika8 = 1028;
var südamerika8 = 1132.6;
var europa8 = 4965.7;
var nordamerika8 = 6600.4;
var asien8 = 12954.7;
var australien8 = 1993;
console.log(afrika + südamerika + europa + nordamerika + asien + australien);
var ds = "das sind ";
var dw = " der gesamten Emissionen ";
var kg = " kg ";
var gesamt = afrika + südamerika + europa + nordamerika + asien + australien;
var mehr = " mehr als 2008 ";
var de = " die Emissionen ";
var oder = " oder ";
var weniger = " weniger als 2008 ";
var af8 = "die Emissionen Afrikas liegen bei ";
console.log(af8 + afrika + kg);
var gesamt = afrika + südamerika + europa + nordamerika + asien + australien;
var ar8 = (afrika / gesamt) * 100;
var prozent = "%";
console.log(ds + ar8 + prozent + dw);
var ad = (afrika - afrika8);
console.log(ds + ad + kg + oder + afrika8 / ad + prozent + mehr);
var sa8 = "die Emissionen Südamerikas liegen bei ";
console.log(sa8 + südamerika + kg);
var sar8 = (südamerika / gesamt) * 100;
var prozent = "%";
console.log(ds + sar8 + prozent + dw);
var adsa = (südamerika - südamerika8);
console.log(ds + adsa + kg + oder + südamerika8 / adsa + prozent + mehr);
var eu8 = "die Emissionen Europas liegen bei ";
console.log(eu8 + europa + kg);
var eur8 = (europa / gesamt) * 100;
var prozent = "%";
console.log(ds + eur8 + prozent + dw);
var adeu = (europa8 - europa);
console.log(ds + adeu + kg + oder + europa8 / adeu + prozent + weniger);
var us8 = "die Emissionen Nordamerikas liegen bei ";
console.log(us8 + nordamerika + kg);
var usr8 = (nordamerika / gesamt) * 100;
var prozent = "%";
console.log(ds + usr8 + prozent + dw);
var adus = (nordamerika8 - nordamerika);
console.log(ds + adus + kg + oder + nordamerika8 / adeu + prozent + weniger);
var as8 = "die Emissionen Asiens liegen bei ";
console.log(as8 + asien + kg);
var asr8 = (asien / gesamt) * 100;
var prozent = "%";
console.log(ds + asr8 + prozent + dw);
var asd = (asien - asien8);
console.log(ds + asd + kg + oder + asien8 / asd + prozent + mehr);
var aus8 = "die Emissionen Australiens liegen bei ";
console.log(aus8 + australien + kg);
var ausr8 = (australien / gesamt) * 100;
var prozent = "%";
console.log(ds + ausr8 + prozent + dw);
var ausd = (australien - australien8);
console.log(ds + ausd + kg + oder + australien8 / ausd + prozent + mehr);
//# sourceMappingURL=emissionen.js.map